### ISSUE TITLE
Kanban board for our Ruby group project

### ISSUE THREAD

**Issue by AmineDerbal** [Leeoasis/Ruby-catalogue#5]
Link to the GitHub project : https://github.com/Leeoasis/Ruby-catalogue 👍 
link to the Kanban board : https://github.com/Leeoasis/Ruby-catalogue/projects/1 👍 
There are three collaborators in this project : @AmineDerbal @Leeoasis @Lornakaboro 
Book tasks => @Leeoasis , Game tasks => @Lornakaboro , Music album tasks @AmineDerbal  👍

**Comment by AlphaNtihinduka** [comment]
## Hello Team🙋‍♂️
Good job working on implementing the Kanban board. You have done incredibly well. 👏  

TO HIGHLIGHT:
- Fair distribution of the card tasks ✔️ 
- Assigned the group tasks to all the members ✔️ 

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- [ ] You have done very great to use the Ruby kanban board template provided. However, according to the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#project-requirements) each task/requirement should be a separate card. Therefore, I kindly suggest to consider splitting the cards to the specific project activity. This will help you to track the progress of each team member during project development ☺️.

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

**Comment by AmineDerbal** [comment]
- [x ] Create cards for all tasks

**Comment by muneebulrehman** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Fair distribution of tasks
- All tasks included in the board
- Good follow-up with the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
